import React from 'react'
import TextInput from '../../src/Text input.js'

import StyleGuideMixin from '../../lib/rsg-mixin'

/**
 * Concrete example component that wraps around its base component to provide
 * styleguide examples.
 *
 * Generally you do not want to mix in your examples with your base component because:
 *  - will add to the overall library size, esp with multiple examples
 *  - has no particular use in production
 *  - adds parsing overhead
 *
 * Essentially, keep the examples components separate from the base ones.
 *
 * @todo Change to es6 classes when the following is resolved:
 * https://github.com/reactjs/react-docgen/issues/10
 */
const TextInputExample = React.createClass({
  mixins: [StyleGuideMixin(TextInput)],
  displayName: 'TextInputExample',
  statics: {
    styleguide: {
      // Code to go into default tab
      code: `<TextInput text={String} />`,
      className: 'apply the css class',
      // Array of additional example tabs
      examples: [
        {
          tabTitle: 'Tab title',
          props: {
            text: 'Prop to assign to the rendered example component',
            children: `React child elements to insert into the component. If specified, auto-code generation is disabled.`
          },
          code: '<TextInput text="Prop to assign to the rendered example component" />'
        },
        {
          tabTitle: 'Auto-generated code',
          props: {
            text: 'This example is auto-generated by not specifying the code property in the example object!'
          }
        }
      ]
    }
  },
  //This render is used for the 'default' tab
  //Recommended that {...this.props} is used so example props can propagate though
  render: function () {
    return (
      <TextInput {...this.props} />
    )
  }
})

module.exports = TextInputExample
